-- Hotel CMS database schema
-- MySQL 5.7+ / MariaDB 10.3+

CREATE TABLE IF NOT EXISTS `admin_users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL UNIQUE,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `last_login` TIMESTAMP NULL DEFAULT NULL,
  `is_active` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `idx_username` (`username`),
  INDEX `idx_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `site_settings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `setting_key` VARCHAR(100) NOT NULL UNIQUE,
  `setting_value` TEXT,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_setting_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rooms` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL UNIQUE,
  `price` DECIMAL(10,2) NOT NULL,
  `room_type` VARCHAR(50) DEFAULT NULL,
  `max_guests` INT(11) DEFAULT NULL,
  `description` TEXT,
  `short_description` TEXT,
  `main_image` VARCHAR(255) DEFAULT NULL,
  `gallery_images` TEXT DEFAULT NULL COMMENT 'JSON array of image paths',
  `features` TEXT DEFAULT NULL COMMENT 'JSON array of features',
  `amenities` TEXT DEFAULT NULL COMMENT 'JSON array of amenities',
  `tags` TEXT DEFAULT NULL COMMENT 'JSON array of tags',
  `included_items` TEXT DEFAULT NULL COMMENT 'JSON array of included items',
  `good_to_know` TEXT DEFAULT NULL COMMENT 'JSON object',
  `book_url` TEXT DEFAULT NULL,
  `original_price` DECIMAL(10,2) DEFAULT NULL,
  `urgency_message` TEXT DEFAULT NULL,
  `rating` INT(1) DEFAULT 5,
  `rating_score` DECIMAL(3,1) DEFAULT NULL,
  `location` VARCHAR(255) DEFAULT NULL,
  `size` VARCHAR(255) DEFAULT NULL,
  `is_featured` TINYINT(1) DEFAULT 0,
  `is_active` TINYINT(1) DEFAULT 1,
  `display_order` INT(11) DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `page_sections` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `page` VARCHAR(50) NOT NULL,
  `section_key` VARCHAR(100) NOT NULL,
  `content_type` ENUM('text', 'html', 'image', 'json') DEFAULT 'text',
  `content` TEXT,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_page_section` (`page`, `section_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `media` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(255) NOT NULL,
  `original_name` VARCHAR(255) DEFAULT NULL,
  `file_path` VARCHAR(500) NOT NULL,
  `file_type` VARCHAR(50) DEFAULT NULL,
  `file_size` INT(11) DEFAULT NULL,
  `uploaded_by` INT(11) DEFAULT NULL,
  `uploaded_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_file_path` (`file_path`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Default admin: admin / password  (change immediately after first login)
-- Hash below is bcrypt for the string `password` (Laravel factory example hash).
INSERT INTO `admin_users` (`username`, `email`, `password_hash`, `is_active`) VALUES
('admin', 'admin@examplehotel.local', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1)
ON DUPLICATE KEY UPDATE `username` = `username`;

-- Default site settings
INSERT INTO `site_settings` (`setting_key`, `setting_value`) VALUES
('site_name', 'Lorem Ipsum Hotel'),
('site_tagline', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
('room_detail_hero_badge', 'Lorem Collection'),
('currency_symbol', '$'),
('footer_tagline', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.'),
('footer_address', '123 Lorem Avenue
Ipsum City, Country'),
('footer_phone', '+1 555 010 0000'),
('footer_email', 'hello@example.com'),
('footer_copyright', '© 2026 Lorem Ipsum Hotel. All rights reserved.'),
('contact_email', 'hello@example.com'),
('whatsapp_number', ''),
('whatsapp_link', ''),
('nav_suites_label', 'Suites'),
('nav_dining_label', 'Dining'),
('nav_experience_label', 'Amenities'),
('nav_events_label', 'Gallery'),
('nav_suites_href', '/rooms'),
('nav_dining_href', '/dining'),
('nav_experience_href', '/amenities'),
('nav_events_href', '/gallery'),
('nav_cta_label', 'Book Now'),
('nav_cta_href', '/rooms'),
('footer_privacy_href', '/privacy-policy'),
('footer_terms_href', '/terms-and-conditions'),
('social_media_json', '[]'),
('google_maps_api_key', ''),
('smtp_host', ''),
('smtp_port', '587'),
('smtp_username', ''),
('smtp_password', ''),
('smtp_encryption', 'tls'),
('smtp_from_email', ''),
('smtp_from_name', 'Lorem Ipsum Hotel'),
('cms_product_name', 'Hotel CMS'),
('theme_primary_color', '#411d13'),
('theme_primary_light_color', '#5a2a1f'),
('theme_background_light_color', '#efe8d6'),
('theme_background_dark_color', '#1a1210'),
('theme_champagne_color', '#f5ede0'),
('theme_text_main_color', '#363636'),
('theme_text_muted_color', '#5c5c5c'),
('theme_surface_light_color', '#ffffff'),
('theme_surface_dark_color', '#2a1f1c'),
('theme_surface_ink_color', '#2a1814'),
('theme_sand_darker_color', '#e3dcc8'),
('theme_display_font', 'Plus Jakarta Sans'),
('theme_serif_font', 'Playfair Display'),
('theme_body_font', 'Noto Sans'),
('booking_wrapper_id', 'booking-shell'),
('header_scripts', ''),
('body_scripts', ''),
('footer_scripts', ''),
('site_logo', ''),
('site_logo_light', ''),
('site_favicon', '')
ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);

-- Default page sections
INSERT INTO `page_sections` (`page`, `section_key`, `content_type`, `content`) VALUES
('index', 'hero_kicker', 'text', 'Lorem Ipsum'),
('index', 'hero_title', 'html', 'Lorem Ipsum <br/><span class="italic text-primary site-hero-accent-text">Dolor Sit</span>'),
('index', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('index', 'hero_cta_text', 'text', 'Explore Rooms'),
('index', 'hero_cta_href', 'text', '/rooms'),
('index', 'hero_bg', 'image', 'assets/images/placeholders/placeholder-hero.svg'),
('index', 'hero_bg_slides', 'json', '[]'),
('index', 'hero_youtube_url', 'text', ''),
('index', 'home_philosophy_kicker', 'text', 'Lorem Ipsum'),
('index', 'home_philosophy_title_html', 'html', 'Lorem Ipsum <br/> Dolor Sit'),
('index', 'home_philosophy_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('index', 'home_philosophy_link_text', 'text', 'Learn More'),
('index', 'home_philosophy_link_href', 'text', '/about'),
('index', 'home_philosophy_main_img', 'image', 'assets/images/placeholders/placeholder-detail.svg'),
('index', 'home_philosophy_secondary_img', 'image', 'assets/images/placeholders/placeholder-gallery.svg'),
('index', 'home_arch_image', 'image', 'assets/images/placeholders/placeholder-hero.svg'),
('index', 'home_arch_badge_title', 'text', 'Lorem'),
('index', 'home_arch_badge_sub', 'text', 'Ipsum'),
('index', 'home_arch_title', 'text', 'Dolor Sit Amet'),
('index', 'home_arch_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('index', 'home_arch_list_1', 'text', 'Lorem ipsum dolor'),
('index', 'home_arch_list_2', 'text', 'Sit amet consectetur'),
('index', 'home_rooms_kicker', 'text', 'Accommodations'),
('index', 'home_rooms_title', 'text', 'Lorem Rooms'),
('index', 'home_rooms_view_all_href', 'text', '/rooms'),
('index', 'home_dining_image', 'image', 'assets/images/placeholders/placeholder-gallery.svg'),
('index', 'home_dining_kicker', 'text', 'Dining'),
('index', 'home_dining_title', 'text', 'Lorem Dining'),
('index', 'home_dining_body_html', 'html', 'Lorem ipsum dolor sit amet, <span class="text-text-main font-semibold">consectetur adipiscing</span> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('index', 'home_dining_cta1', 'text', 'Learn More'),
('index', 'home_dining_cta1_href', 'text', '/dining'),
('index', 'home_dining_cta2', 'text', 'View Details'),
('index', 'home_dining_cta2_href', 'text', '/dining'),
('index', 'booking_widget_html', 'html', ''),
('about', 'page_title', 'text', 'About'),
('about', 'hero_established', 'text', 'Established 2024'),
('about', 'hero_title_html', 'html', 'Lorem Ipsum <br/><span class="font-bold italic text-primary/90 site-hero-accent-text">Dolor Sit</span>'),
('about', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('about', 'hero_bg', 'image', 'assets/images/placeholders/placeholder-hero.svg'),
('about', 'story_title_html', 'html', 'Lorem Ipsum <br/><span class="font-semibold text-primary">Dolor Sit</span>'),
('about', 'story_p1', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('about', 'story_p2', 'text', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'),
('about', 'story_image', 'image', 'assets/images/placeholders/placeholder-detail.svg'),
('about', 'story_quote', 'text', '"Lorem ipsum dolor sit amet, consectetur adipiscing elit."'),
('about', 'values_kicker', 'text', 'Lorem Ipsum'),
('about', 'values_title', 'text', 'Dolor Sit Amet'),
('about', 'values_image', 'image', 'assets/images/placeholders/placeholder-gallery.svg'),
('about', 'values_card_icon', 'text', 'spa'),
('about', 'values_card_title', 'text', 'Lorem Ipsum Dolor'),
('about', 'values_card_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('about', 'values_card_link', 'text', 'Learn More'),
('about', 'values_card_link_href', 'text', '/amenities'),
('about', 'journey_title_html', 'html', 'Lorem <span class="font-bold italic text-primary">Ipsum</span>'),
('about', 'journey_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('about', 'team_kicker', 'text', 'Gallery'),
('about', 'team_heading', 'text', 'Lorem Ipsum'),
('about', 'team_intro', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('about', 'parallax_bg', 'image', 'assets/images/placeholders/placeholder-hero.svg'),
('about', 'parallax_quote', 'text', '"Lorem ipsum dolor sit amet."'),
('about', 'cta_title', 'text', 'Lorem Ipsum Dolor'),
('about', 'cta_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('about', 'cta_btn1', 'text', 'Explore Rooms'),
('about', 'cta_btn1_href', 'text', '/rooms'),
('about', 'cta_btn2', 'text', 'Contact Us'),
('about', 'cta_btn2_href', 'text', '/contact'),
('contact', 'page_title', 'text', 'Contact Us'),
('contact', 'intro_kicker', 'text', 'Lorem Ipsum'),
('contact', 'intro_title', 'text', 'Get in Touch'),
('contact', 'intro_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('contact', 'address_html', 'html', '123 Lorem Avenue<br/>
Ipsum City<br/>
Country'),
('contact', 'map_address', 'text', '123 Lorem Avenue, Ipsum City, Country'),
('contact', 'map_embed_url', 'text', ''),
('contact', 'directions_href', 'text', '#'),
('contact', 'concierge_phone', 'text', '+1 555 010 0000'),
('contact', 'inquiries_email', 'text', 'hello@example.com'),
('contact', 'map_image', 'image', 'assets/images/placeholders/placeholder-gallery.svg'),
('contact', 'map_pin_label', 'text', 'Lorem Location'),
('hotel-policy', 'page_title', 'text', 'Hotel Policy'),
('hotel-policy', 'hero_kicker', 'text', 'Policy'),
('hotel-policy', 'hero_title', 'text', 'Hotel Policy'),
('hotel-policy', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
('hotel-policy', 'last_updated', 'text', 'Last updated: April 18, 2026'),
('hotel-policy', 'body_html', 'html', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h2>Lorem Ipsum</h2><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'),
('privacy-policy', 'page_title', 'text', 'Privacy Policy'),
('privacy-policy', 'hero_kicker', 'text', 'Legal'),
('privacy-policy', 'hero_title', 'text', 'Privacy Policy'),
('privacy-policy', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
('privacy-policy', 'last_updated', 'text', 'Last updated: April 18, 2026'),
('privacy-policy', 'body_html', 'html', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h2>Lorem Ipsum</h2><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'),
('terms-and-conditions', 'page_title', 'text', 'Terms & Conditions'),
('terms-and-conditions', 'hero_kicker', 'text', 'Legal'),
('terms-and-conditions', 'hero_title', 'text', 'Terms & Conditions'),
('terms-and-conditions', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
('terms-and-conditions', 'last_updated', 'text', 'Last updated: April 18, 2026'),
('terms-and-conditions', 'body_html', 'html', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h2>Lorem Ipsum</h2><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'),
('gallery', 'page_title', 'text', 'Gallery'),
('gallery', 'hero_kicker', 'text', 'Lorem Ipsum'),
('gallery', 'hero_title_html', 'html', 'VISUAL <span class="font-bold italic text-primary">LOREM</span>'),
('gallery', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('gallery', 'hero_bg', 'image', 'assets/images/placeholders/placeholder-hero.svg'),
('dining', 'page_title', 'text', 'Dining'),
('dining', 'hero_kicker', 'text', 'Dining'),
('dining', 'hero_title_html', 'html', 'Lorem Ipsum <br/><i class="font-light opacity-90">Dolor Sit</i>'),
('dining', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('dining', 'hero_hours', 'text', 'Open Daily: 00:00 - 00:00'),
('dining', 'hero_bg', 'image', 'assets/images/placeholders/placeholder-hero.svg'),
('dining', 'intro_vertical', 'text', 'Lorem Menus'),
('dining', 'chef_title_html', 'html', 'Lorem <br/> <span class="text-primary italic">Ipsum</span>'),
('dining', 'chef_body_html', 'html', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'),
('dining', 'chef_signature', 'text', 'Lorem Ipsum'),
('dining', 'chef_main_img', 'image', 'assets/images/placeholders/placeholder-detail.svg'),
('dining', 'chef_circle_img', 'image', 'assets/images/placeholders/placeholder-gallery.svg'),
('dining', 'visual_title', 'text', 'Lorem Gallery'),
('dining', 'visual_link_href', 'text', '/gallery'),
('dining', 'menu_kicker', 'text', 'Lorem Menu'),
('dining', 'menu_heading', 'text', 'Lorem Ipsum'),
('dining', 'menu_quote', 'text', '"Lorem ipsum dolor sit amet."'),
('dining', 'cta_bg', 'image', 'assets/images/placeholders/placeholder-room.svg'),
('dining', 'cta_title', 'text', 'Lorem Reservation'),
('dining', 'cta_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('dining', 'cta_btn1', 'text', 'Contact Us'),
('dining', 'cta_btn1_href', 'text', '/contact'),
('dining', 'cta_btn2', 'text', 'Explore Rooms'),
('dining', 'sticky_kicker', 'text', 'Lorem'),
('dining', 'sticky_subtitle', 'text', 'Ipsum'),
('rooms', 'page_title', 'text', 'Rooms & Suites'),
('rooms', 'hero_title', 'html', 'Lorem Spaces <br/><span class="font-bold italic font-serif">Dolor Sit</span>'),
('rooms', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
('rooms', 'hero_bg', 'image', 'assets/images/placeholders/placeholder-hero.svg'),
('amenities', 'page_title', 'text', 'Amenities'),
('about', 'timeline_json', 'json', '[{"year":"2021","kind":"circle","title":"Lorem Ipsum","body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."},{"year":"2022","kind":"dot","title":"Dolor Sit","body":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."},{"year":"2023","kind":"circle","title":"Amet Elit","body":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."},{"year":"2024","kind":"dot_primary","title":"Tempor Incididunt","body":"Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}]'),
('about', 'team_json', 'json', '["assets/images/placeholders/placeholder-gallery.svg","assets/images/placeholders/placeholder-detail.svg","assets/images/placeholders/placeholder-room.svg"]'),
('gallery', 'items_json', 'json', '["assets/images/placeholders/placeholder-gallery.svg","assets/images/placeholders/placeholder-hero.svg","assets/images/placeholders/placeholder-detail.svg","assets/images/placeholders/placeholder-room.svg","assets/images/placeholders/placeholder-gallery.svg","assets/images/placeholders/placeholder-detail.svg"]'),
('dining', 'masonry_json', 'json', '[{"src":"assets/images/placeholders/placeholder-gallery.svg","tag":"Lorem","caption":"Lorem Ipsum"},{"src":"assets/images/placeholders/placeholder-detail.svg","tag":"Dolor","caption":"Dolor Sit"},{"src":"assets/images/placeholders/placeholder-room.svg","tag":"","caption":""},{"src":"assets/images/placeholders/placeholder-hero.svg","tag":"","caption":""},{"src":"assets/images/placeholders/placeholder-gallery.svg","tag":"","caption":""}]'),
('dining', 'menu_json', 'json', '[{"name":"Lorem Ipsum I","desc":"Lorem ipsum dolor sit amet, consectetur adipiscing elit.","price":"$00"},{"name":"Dolor Sit II","desc":"Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.","price":"$00"},{"name":"Amet Elit III","desc":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.","price":"$00"},{"name":"Tempor IV","desc":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum.","price":"$00"}]'),
('amenities', 'sections_json', 'json', '[{"bg":"assets/images/placeholders/placeholder-hero.svg","gradient":"linear-gradient(rgba(15, 15, 10, 0.3) 0%, rgba(15, 15, 10, 0.8) 100%)","kicker":"01 / Lorem","icon":"restaurant","title_html":"Lorem <br/> <span class=\"font-bold text-outline\">Ipsum</span>","body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.","btn":"Learn More","btn_href":"/dining","layout":"bottom"},{"bg":"assets/images/placeholders/placeholder-detail.svg","gradient":"linear-gradient(rgba(20, 15, 5, 0.5) 0%, rgba(0, 0, 0, 0.6) 100%)","kicker":"02 / Dolor","icon":"local_bar","title_html":"Dolor <br/> <span class=\"font-bold text-outline\">Sit</span>","body":"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","btn":"Learn More","btn_href":"/amenities","layout":"right"},{"bg":"assets/images/placeholders/placeholder-gallery.svg","gradient":"linear-gradient(to right, rgba(0, 0, 0, 0.7) 0%, rgba(0, 0, 0, 0.2) 100%)","kicker":"03 / Amet","icon":"pool","title_html":"Amet <br/> <span class=\"font-bold text-outline\">Elit</span>","body":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.","btn":"Learn More","btn_href":"/gallery","layout":"top"},{"bg":"assets/images/placeholders/placeholder-room.svg","gradient":"linear-gradient(to top, rgba(10, 10, 10, 0.9) 0%, rgba(10, 10, 10, 0.2) 100%)","kicker":"04 / Tempor","icon":"fitness_center","title_html":"Tempor <span class=\"font-bold text-outline\">Incididunt</span>","body":"Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.","btn":"Learn More","btn_href":"/rooms","layout":"center"}]')
ON DUPLICATE KEY UPDATE `content` = VALUES(`content`), `content_type` = VALUES(`content_type`);

-- Default demo rooms
INSERT INTO `rooms` (`title`, `slug`, `price`, `room_type`, `max_guests`, `description`, `short_description`, `main_image`, `gallery_images`, `features`, `amenities`, `tags`, `included_items`, `good_to_know`, `book_url`, `urgency_message`, `size`, `location`, `is_featured`, `is_active`, `display_order`) VALUES
('Lorem Room One', 'lorem-room-one', 100.00, 'Standard', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'assets/images/placeholders/placeholder-room.svg', '["assets/images/placeholders/placeholder-detail.svg","assets/images/placeholders/placeholder-gallery.svg"]', '["35 SQM","Queen Bed","City View","Wi-Fi"]', '[]', '[]', '[]', '{}', 'contact.php', '', '35 SQM', 'City View', 1, 1, 10),
('Lorem Room Two', 'lorem-room-two', 150.00, 'Suite', 3, 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'assets/images/placeholders/placeholder-detail.svg', '["assets/images/placeholders/placeholder-room.svg","assets/images/placeholders/placeholder-gallery.svg"]', '["48 SQM","King Bed","Lounge Area","Wi-Fi"]', '[]', '[]', '[]', '{}', 'contact.php', '', '48 SQM', 'Upper Floor', 1, 1, 20),
('Lorem Room Three', 'lorem-room-three', 220.00, 'Premium', 4, 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.', 'assets/images/placeholders/placeholder-gallery.svg', '["assets/images/placeholders/placeholder-room.svg","assets/images/placeholders/placeholder-detail.svg"]', '["60 SQM","Twin Lounge","Corner View","Wi-Fi"]', '[]', '[]', '[]', '{}', 'contact.php', '', '60 SQM', 'Corner View', 1, 1, 30)
ON DUPLICATE KEY UPDATE `slug` = `slug`;

