<?php
/**
 * Default CMS seed data for fresh deployments.
 * Used by tools/seed_cms_defaults.php — does not overwrite existing rows (INSERT IGNORE).
 */

$cmsDefaults = require __DIR__ . '/cms-defaults.php';

$heroPlaceholder = (string) cms_default_setting('placeholder_hero_image');
$roomPlaceholder = (string) cms_default_setting('placeholder_room_image');
$detailPlaceholder = (string) cms_default_setting('placeholder_detail_image');
$galleryPlaceholder = (string) cms_default_setting('placeholder_gallery_image');

$siteSettings = [
    'site_name' => cms_default_setting('site_name'),
    'site_tagline' => cms_default_setting('site_tagline'),
    'room_detail_hero_badge' => cms_default_setting('room_detail_hero_badge'),
    'currency_symbol' => cms_default_setting('currency_symbol'),
    'footer_tagline' => cms_default_setting('footer_tagline'),
    'footer_address' => cms_default_setting('footer_address'),
    'footer_phone' => cms_default_setting('footer_phone'),
    'footer_email' => cms_default_setting('footer_email'),
    'footer_copyright' => cms_default_setting('footer_copyright'),
    'contact_email' => cms_default_setting('contact_email'),
    'whatsapp_number' => cms_default_setting('whatsapp_number'),
    'whatsapp_link' => cms_default_setting('whatsapp_link'),
    'nav_suites_label' => cms_default_setting('nav_suites_label'),
    'nav_dining_label' => cms_default_setting('nav_dining_label'),
    'nav_experience_label' => cms_default_setting('nav_experience_label'),
    'nav_events_label' => cms_default_setting('nav_events_label'),
    'nav_suites_href' => cms_default_setting('nav_suites_href'),
    'nav_dining_href' => cms_default_setting('nav_dining_href'),
    'nav_experience_href' => cms_default_setting('nav_experience_href'),
    'nav_events_href' => cms_default_setting('nav_events_href'),
    'nav_story_label' => cms_default_setting('nav_story_label'),
    'nav_story_href' => cms_default_setting('nav_story_href'),
    'nav_cta_label' => cms_default_setting('nav_cta_label'),
    'nav_cta_href' => cms_default_setting('nav_cta_href'),
    'site_brand_collection_line' => cms_default_setting('site_brand_collection_line'),
    'footer_line_2' => cms_default_setting('footer_line_2'),
    'footer_careers_href' => cms_default_setting('footer_careers_href'),
    'footer_sustainability_href' => cms_default_setting('footer_sustainability_href'),
    'footer_privacy_href' => cms_default_setting('footer_privacy_href'),
    'footer_terms_href' => cms_default_setting('footer_terms_href'),
    'page_active_about' => cms_default_setting('page_active_about'),
    'page_active_rooms' => cms_default_setting('page_active_rooms'),
    'page_active_contact' => cms_default_setting('page_active_contact'),
    'page_active_gallery' => cms_default_setting('page_active_gallery'),
    'page_active_dining' => cms_default_setting('page_active_dining'),
    'page_active_amenities' => cms_default_setting('page_active_amenities'),
    'page_active_hotel-policy' => cms_default_setting('page_active_hotel-policy'),
    'page_active_privacy-policy' => cms_default_setting('page_active_privacy-policy'),
    'page_active_terms-and-conditions' => cms_default_setting('page_active_terms-and-conditions'),
    'maintenance_mode' => cms_default_setting('maintenance_mode'),
    'maintenance_title' => cms_default_setting('maintenance_title'),
    'maintenance_message' => cms_default_setting('maintenance_message'),
    'maintenance_background' => cms_default_setting('maintenance_background'),
    'social_media_json' => '[]',
    'google_maps_api_key' => '',
    'smtp_host' => '',
    'smtp_port' => '587',
    'smtp_username' => '',
    'smtp_password' => '',
    'smtp_encryption' => 'tls',
    'smtp_from_email' => '',
    'smtp_from_name' => cms_default_setting('smtp_from_name'),
    'cms_product_name' => CMS_PRODUCT_NAME,
    'theme_primary_color' => cms_default_setting('theme_primary_color'),
    'theme_primary_light_color' => cms_default_setting('theme_primary_light_color'),
    'theme_background_light_color' => cms_default_setting('theme_background_light_color'),
    'theme_background_dark_color' => cms_default_setting('theme_background_dark_color'),
    'theme_champagne_color' => cms_default_setting('theme_champagne_color'),
    'theme_text_main_color' => cms_default_setting('theme_text_main_color'),
    'theme_text_muted_color' => cms_default_setting('theme_text_muted_color'),
    'theme_surface_light_color' => cms_default_setting('theme_surface_light_color'),
    'theme_surface_dark_color' => cms_default_setting('theme_surface_dark_color'),
    'theme_surface_ink_color' => cms_default_setting('theme_surface_ink_color'),
    'theme_sand_darker_color' => cms_default_setting('theme_sand_darker_color'),
    'theme_display_font' => cms_default_setting('theme_display_font'),
    'theme_serif_font' => cms_default_setting('theme_serif_font'),
    'theme_body_font' => cms_default_setting('theme_body_font'),
    'booking_wrapper_id' => cms_default_setting('booking_wrapper_id'),
    'header_scripts' => '',
    'body_scripts' => '',
    'footer_scripts' => '',
    'site_logo' => '',
    'site_logo_light' => '',
    'site_favicon' => '',
];

$jsonEncode = static function ($data) {
    return json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
};

$homeBentoDefault = [
    ['image' => $heroPlaceholder, 'title' => 'The Infinity Pool', 'subtitle' => 'Open Daily • 6AM - 10PM'],
    ['image' => $detailPlaceholder, 'title' => 'Wellness Spa', 'subtitle' => ''],
    ['image' => $galleryPlaceholder, 'title' => 'Elite Gym', 'subtitle' => ''],
    ['image' => $roomPlaceholder, 'title' => 'Akassa Hall', 'subtitle' => 'Business & Events'],
];
$homeLocationBulletsDefault = ['5 min to Government House', '15 min to Airport', 'Oxbow Lake waterfront'];

$pageSections = [
    ['index', 'hero_trust_badge', 'text', 'Travelers Choice 2026'],
    ['index', 'hero_show_stars', 'text', '1'],
    ['index', 'hero_title', 'html', 'Lorem on the Shores<br/><span class="italic text-surface">of the Lake.</span>'],
    ['index', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['index', 'hero_bg', 'image', $heroPlaceholder],
    ['index', 'hero_gallery_slides_json', 'json', $jsonEncode([$heroPlaceholder, $detailPlaceholder, $galleryPlaceholder])],
    ['index', 'home_booking_guarantee_line', 'text', 'Best Rate Guarantee'],
    ['index', 'home_philosophy_kicker', 'text', 'Our Heritage'],
    ['index', 'home_philosophy_title_html', 'html', 'Where Heritage Meets Hospitality'],
    ['index', 'home_philosophy_body', 'html', '<p>Nestled in the heart of Bayelsa State, our hotel blends rich heritage with modern hospitality. As part of the Best Western <span class="text-brand-red font-semibold">Plus</span> collection, we uphold a legacy of excellence while delivering a distinctively Nigerian warmth.</p>'],
    ['index', 'home_philosophy_link_text', 'text', 'Explore the Story'],
    ['index', 'home_philosophy_link_href', 'text', '/about'],
    ['index', 'home_philosophy_main_img', 'image', $detailPlaceholder],
    ['index', 'home_rooms_kicker', 'text', 'Exquisite suites designed for the refined traveler'],
    ['index', 'home_rooms_title', 'text', 'Sanctuaries of Calm'],
    ['index', 'home_rooms_view_all_href', 'text', '/rooms'],
    ['index', 'home_dining_kicker', 'text', 'Gastronomy'],
    ['index', 'home_dining_heading_html', 'html', '<span class="italic">Culinary Excellence</span>'],
    ['index', 'home_dining_venue1_title', 'text', 'Mama Oxbow'],
    ['index', 'home_dining_venue1_body', 'text', 'Authentic local delicacies crafted with a modern touch, overlooking the gentle ripples of the lake.'],
    ['index', 'home_dining_venue2_title', 'text', 'Red Lotus'],
    ['index', 'home_dining_venue2_body', 'text', 'An Asian-fusion journey where tradition meets contemporary culinary innovation.'],
    ['index', 'home_dining_image_top', 'image', $galleryPlaceholder],
    ['index', 'home_dining_image_bottom', 'image', $detailPlaceholder],
    ['index', 'home_facilities_title', 'text', 'Leisure & Wellness'],
    ['index', 'home_facilities_blurb', 'text', 'Designed to rejuvenate your senses and enhance your productivity.'],
    ['index', 'home_facilities_bento_json', 'json', $jsonEncode($homeBentoDefault)],
    ['index', 'home_location_title', 'text', 'The Serenity of Oxbow Lake'],
    ['index', 'home_location_body', 'text', 'A peaceful retreat away from the city\'s pulse, offering breathtaking views and tranquil mornings.'],
    ['index', 'home_location_bullets_json', 'json', $jsonEncode($homeLocationBulletsDefault)],
    ['index', 'home_location_address', 'text', 'Oxbow Lake Rd, Yenagoa, Bayelsa'],
    ['index', 'home_location_map_image', 'image', $galleryPlaceholder],
    ['index', 'home_location_map_embed_url', 'text', ''],
    ['index', 'booking_widget_html', 'html', ''],

    ['about', 'page_title', 'text', 'About'],
    ['about', 'hero_established', 'text', 'Established 2024'],
    ['about', 'hero_title_html', 'html', 'Lorem Ipsum <br/><span class="font-bold italic text-primary/90 site-hero-accent-text">Dolor Sit</span>'],
    ['about', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['about', 'hero_bg', 'image', $heroPlaceholder],
    ['about', 'story_title_html', 'html', 'Lorem Ipsum <br/><span class="font-semibold text-primary">Dolor Sit</span>'],
    ['about', 'story_p1', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['about', 'story_p2', 'text', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'],
    ['about', 'story_image', 'image', $detailPlaceholder],
    ['about', 'story_quote', 'text', '"Lorem ipsum dolor sit amet, consectetur adipiscing elit."'],
    ['about', 'values_kicker', 'text', 'Lorem Ipsum'],
    ['about', 'values_title', 'text', 'Dolor Sit Amet'],
    ['about', 'values_image', 'image', $galleryPlaceholder],
    ['about', 'values_card_icon', 'text', 'spa'],
    ['about', 'values_card_title', 'text', 'Lorem Ipsum Dolor'],
    ['about', 'values_card_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['about', 'values_card_link', 'text', 'Learn More'],
    ['about', 'values_card_link_href', 'text', '/amenities'],
    ['about', 'journey_title_html', 'html', 'Lorem <span class="font-bold italic text-primary">Ipsum</span>'],
    ['about', 'journey_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['about', 'team_kicker', 'text', 'Gallery'],
    ['about', 'team_heading', 'text', 'Lorem Ipsum'],
    ['about', 'team_intro', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['about', 'parallax_bg', 'image', $heroPlaceholder],
    ['about', 'parallax_quote', 'text', '"Lorem ipsum dolor sit amet."'],
    ['about', 'cta_title', 'text', 'Lorem Ipsum Dolor'],
    ['about', 'cta_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['about', 'cta_btn1', 'text', 'Explore Rooms'],
    ['about', 'cta_btn1_href', 'text', '/rooms'],
    ['about', 'cta_btn2', 'text', 'Contact Us'],
    ['about', 'cta_btn2_href', 'text', '/contact'],

    ['contact', 'page_title', 'text', 'Contact Us'],
    ['contact', 'intro_kicker', 'text', 'Lorem Ipsum'],
    ['contact', 'intro_title', 'text', 'Get in Touch'],
    ['contact', 'intro_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['contact', 'address_html', 'html', "123 Lorem Avenue<br/>\nIpsum City<br/>\nCountry"],
    ['contact', 'map_address', 'text', '123 Lorem Avenue, Ipsum City, Country'],
    ['contact', 'map_embed_url', 'text', ''],
    ['contact', 'directions_href', 'text', '#'],
    ['contact', 'concierge_phone', 'text', cms_default_setting('footer_phone')],
    ['contact', 'inquiries_email', 'text', cms_default_setting('contact_email')],
    ['contact', 'map_image', 'image', $galleryPlaceholder],
    ['contact', 'map_pin_label', 'text', 'Lorem Location'],

    ['hotel-policy', 'page_title', 'text', 'Hotel Policy'],
    ['hotel-policy', 'hero_kicker', 'text', 'Policy'],
    ['hotel-policy', 'hero_title', 'text', 'Hotel Policy'],
    ['hotel-policy', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'],
    ['hotel-policy', 'last_updated', 'text', 'Last updated: April 18, 2026'],
    ['hotel-policy', 'body_html', 'html', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h2>Lorem Ipsum</h2><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'],

    ['privacy-policy', 'page_title', 'text', 'Privacy Policy'],
    ['privacy-policy', 'hero_kicker', 'text', 'Legal'],
    ['privacy-policy', 'hero_title', 'text', 'Privacy Policy'],
    ['privacy-policy', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'],
    ['privacy-policy', 'last_updated', 'text', 'Last updated: April 18, 2026'],
    ['privacy-policy', 'body_html', 'html', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h2>Lorem Ipsum</h2><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'],

    ['terms-and-conditions', 'page_title', 'text', 'Terms & Conditions'],
    ['terms-and-conditions', 'hero_kicker', 'text', 'Legal'],
    ['terms-and-conditions', 'hero_title', 'text', 'Terms & Conditions'],
    ['terms-and-conditions', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'],
    ['terms-and-conditions', 'last_updated', 'text', 'Last updated: April 18, 2026'],
    ['terms-and-conditions', 'body_html', 'html', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h2>Lorem Ipsum</h2><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'],

    ['gallery', 'page_title', 'text', 'Gallery'],
    ['gallery', 'hero_kicker', 'text', 'Lorem Ipsum'],
    ['gallery', 'hero_title_html', 'html', 'VISUAL <span class="font-bold italic text-primary">LOREM</span>'],
    ['gallery', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['gallery', 'hero_bg', 'image', $heroPlaceholder],

    ['dining', 'page_title', 'text', 'Dining'],
    ['dining', 'hero_kicker', 'text', 'Dining'],
    ['dining', 'hero_title_html', 'html', 'Lorem Ipsum <br/><i class="font-light opacity-90">Dolor Sit</i>'],
    ['dining', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['dining', 'hero_hours', 'text', 'Open Daily: 00:00 - 00:00'],
    ['dining', 'hero_bg', 'image', $heroPlaceholder],
    ['dining', 'intro_vertical', 'text', 'Lorem Menus'],
    ['dining', 'chef_title_html', 'html', 'Lorem <br/> <span class="text-primary italic">Ipsum</span>'],
    ['dining', 'chef_body_html', 'html', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'],
    ['dining', 'chef_signature', 'text', 'Lorem Ipsum'],
    ['dining', 'chef_main_img', 'image', $detailPlaceholder],
    ['dining', 'chef_circle_img', 'image', $galleryPlaceholder],
    ['dining', 'visual_title', 'text', 'Lorem Gallery'],
    ['dining', 'visual_link_href', 'text', '/gallery'],
    ['dining', 'menu_kicker', 'text', 'Lorem Menu'],
    ['dining', 'menu_heading', 'text', 'Lorem Ipsum'],
    ['dining', 'menu_quote', 'text', '"Lorem ipsum dolor sit amet."'],
    ['dining', 'cta_bg', 'image', $roomPlaceholder],
    ['dining', 'cta_title', 'text', 'Lorem Reservation'],
    ['dining', 'cta_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['dining', 'cta_btn1', 'text', 'Contact Us'],
    ['dining', 'cta_btn1_href', 'text', '/contact'],
    ['dining', 'cta_btn2', 'text', 'Explore Rooms'],
    ['dining', 'sticky_kicker', 'text', 'Lorem'],
    ['dining', 'sticky_subtitle', 'text', 'Ipsum'],

    ['rooms', 'page_title', 'text', 'Rooms & Suites'],
    ['rooms', 'hero_title', 'text', 'Rooms & Suites'],
    ['rooms', 'hero_kicker', 'text', 'Accommodations'],
    ['rooms', 'hero_subtitle', 'text', 'Sanctuaries of comfort on the shores of Oxbow Lake'],
    ['rooms', 'signature_badge', 'text', 'Signature Suite'],
    ['rooms', 'signature_kicker', 'text', 'The Pinnacle of Living'],
    ['rooms', 'amenities_reminder_title', 'text', 'All suites include:'],
    ['rooms', 'amenities_reminder_items_json', 'json', '["WIFI","BREAKFAST","TOILETRIES","TURNDOWN"]'],
    ['rooms', 'amenities_reminder_section_classes', 'text', 'bg-surface-container py-[54px]'],
    ['rooms', 'final_cta_section_classes', 'text', 'py-7 my-0 text-center bg-white'],
    ['rooms', 'final_cta_title', 'text', 'Need help choosing?'],
    ['rooms', 'final_cta_body', 'text', 'Our dedicated concierge is available 24/7 to help you select the perfect sanctuary for your stay in Yenagoa.'],
    ['rooms', 'final_cta_label', 'text', 'Contact Reservations'],
    ['rooms', 'final_cta_href', 'text', '/contact'],
    ['rooms', 'hero_bg', 'image', $heroPlaceholder],

    ['amenities', 'page_title', 'text', 'Amenities'],
    ['amenities', 'cta_title', 'text', 'Ready to Experience Our Facilities?'],
    ['amenities', 'cta_btn_label', 'text', 'Book Your Stay'],
    ['amenities', 'cta_btn_href', 'text', '/contact'],
    ['amenities', 'services_kicker', 'text', 'Impeccable Care'],
    ['amenities', 'services_title', 'text', 'Signature Guest Services'],
    ['amenities', 'services_items_json', 'json', '[{"title":"24h Concierge","subtitle":"Dedicated to your every whim"},{"title":"Airport Transfer","subtitle":"Luxury chauffeur fleet"},{"title":"Laundry & Press","subtitle":"Same-day valet service"},{"title":"High-Speed WiFi","subtitle":"Gigabit fiber throughout"},{"title":"Secure Parking","subtitle":"24/7 guarded premises"},{"title":"Room Service","subtitle":"Global dining 24/7"}]'],
];

$pageSections[] = ['about', 'timeline_json', 'json', $jsonEncode($cmsDefaults['about_timeline'])];
$pageSections[] = ['about', 'team_json', 'json', $jsonEncode($cmsDefaults['about_team'])];
$pageSections[] = ['gallery', 'items_json', 'json', $jsonEncode($cmsDefaults['gallery_items'])];
$pageSections[] = ['dining', 'masonry_json', 'json', $jsonEncode($cmsDefaults['dining_masonry'])];
$pageSections[] = ['dining', 'menu_json', 'json', $jsonEncode($cmsDefaults['dining_menu'])];
$pageSections[] = ['amenities', 'sections_json', 'json', $jsonEncode($cmsDefaults['amenities_sections'])];

$rooms = [
    [
        'title' => 'Lorem Room One',
        'slug' => 'lorem-room-one',
        'price' => 100.00,
        'room_type' => 'Standard',
        'max_guests' => 2,
        'short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n\nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        'main_image' => $roomPlaceholder,
        'gallery_images' => [$detailPlaceholder, $galleryPlaceholder],
        'features' => ['35 SQM', 'Queen Bed', 'City View', 'Wi-Fi'],
        'size' => '35 SQM',
        'location' => 'City View',
        'is_featured' => 1,
        'display_order' => 10,
    ],
    [
        'title' => 'Lorem Room Two',
        'slug' => 'lorem-room-two',
        'price' => 150.00,
        'room_type' => 'Suite',
        'max_guests' => 3,
        'short_description' => 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'description' => "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n\nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        'main_image' => $detailPlaceholder,
        'gallery_images' => [$roomPlaceholder, $galleryPlaceholder],
        'features' => ['48 SQM', 'King Bed', 'Lounge Area', 'Wi-Fi'],
        'size' => '48 SQM',
        'location' => 'Upper Floor',
        'is_featured' => 1,
        'display_order' => 20,
    ],
    [
        'title' => 'Lorem Room Three',
        'slug' => 'lorem-room-three',
        'price' => 220.00,
        'room_type' => 'Premium',
        'max_guests' => 4,
        'short_description' => 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
        'description' => "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
        'main_image' => $galleryPlaceholder,
        'gallery_images' => [$roomPlaceholder, $detailPlaceholder],
        'features' => ['60 SQM', 'Twin Lounge', 'Corner View', 'Wi-Fi'],
        'size' => '60 SQM',
        'location' => 'Corner View',
        'is_featured' => 1,
        'display_order' => 30,
    ],
];

return [
    'site_settings' => $siteSettings,
    'page_sections' => $pageSections,
    'rooms' => $rooms,
];
