<?php
/**
 * Default CMS seed data for fresh deployments.
 * Used by tools/seed_cms_defaults.php — does not overwrite existing rows (INSERT IGNORE).
 */

$cmsDefaults = require __DIR__ . '/cms-defaults.php';

$heroPlaceholder = (string) cms_default_setting('placeholder_hero_image');
$roomPlaceholder = (string) cms_default_setting('placeholder_room_image');
$detailPlaceholder = (string) cms_default_setting('placeholder_detail_image');
$galleryPlaceholder = (string) cms_default_setting('placeholder_gallery_image');

$siteSettings = [
    'site_name' => cms_default_setting('site_name'),
    'site_tagline' => cms_default_setting('site_tagline'),
    'room_detail_hero_badge' => cms_default_setting('room_detail_hero_badge'),
    'currency_symbol' => cms_default_setting('currency_symbol'),
    'footer_tagline' => cms_default_setting('footer_tagline'),
    'footer_address' => cms_default_setting('footer_address'),
    'footer_phone' => cms_default_setting('footer_phone'),
    'footer_email' => cms_default_setting('footer_email'),
    'footer_copyright' => cms_default_setting('footer_copyright'),
    'contact_email' => cms_default_setting('contact_email'),
    'whatsapp_number' => cms_default_setting('whatsapp_number'),
    'whatsapp_link' => cms_default_setting('whatsapp_link'),
    'nav_suites_label' => cms_default_setting('nav_suites_label'),
    'nav_dining_label' => cms_default_setting('nav_dining_label'),
    'nav_experience_label' => cms_default_setting('nav_experience_label'),
    'nav_events_label' => cms_default_setting('nav_events_label'),
    'nav_suites_href' => cms_default_setting('nav_suites_href'),
    'nav_dining_href' => cms_default_setting('nav_dining_href'),
    'nav_experience_href' => cms_default_setting('nav_experience_href'),
    'nav_events_href' => cms_default_setting('nav_events_href'),
    'nav_cta_label' => cms_default_setting('nav_cta_label'),
    'nav_cta_href' => cms_default_setting('nav_cta_href'),
    'footer_privacy_href' => cms_default_setting('footer_privacy_href'),
    'footer_terms_href' => cms_default_setting('footer_terms_href'),
    'page_active_about' => cms_default_setting('page_active_about'),
    'page_active_rooms' => cms_default_setting('page_active_rooms'),
    'page_active_contact' => cms_default_setting('page_active_contact'),
    'page_active_gallery' => cms_default_setting('page_active_gallery'),
    'page_active_dining' => cms_default_setting('page_active_dining'),
    'page_active_amenities' => cms_default_setting('page_active_amenities'),
    'page_active_hotel-policy' => cms_default_setting('page_active_hotel-policy'),
    'page_active_privacy-policy' => cms_default_setting('page_active_privacy-policy'),
    'page_active_terms-and-conditions' => cms_default_setting('page_active_terms-and-conditions'),
    'maintenance_mode' => cms_default_setting('maintenance_mode'),
    'maintenance_title' => cms_default_setting('maintenance_title'),
    'maintenance_message' => cms_default_setting('maintenance_message'),
    'maintenance_background' => cms_default_setting('maintenance_background'),
    'social_media_json' => '[]',
    'google_maps_api_key' => '',
    'smtp_host' => '',
    'smtp_port' => '587',
    'smtp_username' => '',
    'smtp_password' => '',
    'smtp_encryption' => 'tls',
    'smtp_from_email' => '',
    'smtp_from_name' => cms_default_setting('smtp_from_name'),
    'cms_product_name' => CMS_PRODUCT_NAME,
    'theme_primary_color' => cms_default_setting('theme_primary_color'),
    'theme_primary_light_color' => cms_default_setting('theme_primary_light_color'),
    'theme_background_light_color' => cms_default_setting('theme_background_light_color'),
    'theme_background_dark_color' => cms_default_setting('theme_background_dark_color'),
    'theme_champagne_color' => cms_default_setting('theme_champagne_color'),
    'theme_text_main_color' => cms_default_setting('theme_text_main_color'),
    'theme_text_muted_color' => cms_default_setting('theme_text_muted_color'),
    'theme_surface_light_color' => cms_default_setting('theme_surface_light_color'),
    'theme_surface_dark_color' => cms_default_setting('theme_surface_dark_color'),
    'theme_surface_ink_color' => cms_default_setting('theme_surface_ink_color'),
    'theme_sand_darker_color' => cms_default_setting('theme_sand_darker_color'),
    'theme_display_font' => cms_default_setting('theme_display_font'),
    'theme_serif_font' => cms_default_setting('theme_serif_font'),
    'theme_body_font' => cms_default_setting('theme_body_font'),
    'booking_wrapper_id' => cms_default_setting('booking_wrapper_id'),
    'header_scripts' => '',
    'body_scripts' => '',
    'footer_scripts' => '',
    'site_logo' => '',
    'site_logo_light' => '',
    'site_favicon' => '',
];

$jsonEncode = static function ($data) {
    return json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
};

$pageSections = [
    ['index', 'hero_kicker', 'text', 'Lorem Ipsum'],
    ['index', 'hero_title', 'html', 'Lorem Ipsum <br/><span class="italic text-primary site-hero-accent-text">Dolor Sit</span>'],
    ['index', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['index', 'hero_cta_text', 'text', 'Explore Rooms'],
    ['index', 'hero_cta_href', 'text', '/rooms'],
    ['index', 'hero_bg', 'image', $heroPlaceholder],
    ['index', 'hero_bg_slides', 'json', '[]'],
    ['index', 'hero_youtube_url', 'text', ''],
    ['index', 'home_philosophy_kicker', 'text', 'Lorem Ipsum'],
    ['index', 'home_philosophy_title_html', 'html', 'Lorem Ipsum <br/> Dolor Sit'],
    ['index', 'home_philosophy_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['index', 'home_philosophy_link_text', 'text', 'Learn More'],
    ['index', 'home_philosophy_link_href', 'text', '/about'],
    ['index', 'home_philosophy_main_img', 'image', $detailPlaceholder],
    ['index', 'home_philosophy_secondary_img', 'image', $galleryPlaceholder],
    ['index', 'home_arch_image', 'image', $heroPlaceholder],
    ['index', 'home_arch_badge_title', 'text', 'Lorem'],
    ['index', 'home_arch_badge_sub', 'text', 'Ipsum'],
    ['index', 'home_arch_title', 'text', 'Dolor Sit Amet'],
    ['index', 'home_arch_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['index', 'home_arch_list_1', 'text', 'Lorem ipsum dolor'],
    ['index', 'home_arch_list_2', 'text', 'Sit amet consectetur'],
    ['index', 'home_rooms_kicker', 'text', 'Accommodations'],
    ['index', 'home_rooms_title', 'text', 'Lorem Rooms'],
    ['index', 'home_rooms_view_all_href', 'text', '/rooms'],
    ['index', 'home_dining_image', 'image', $galleryPlaceholder],
    ['index', 'home_dining_kicker', 'text', 'Dining'],
    ['index', 'home_dining_title', 'text', 'Lorem Dining'],
    ['index', 'home_dining_body_html', 'html', 'Lorem ipsum dolor sit amet, <span class="text-text-main font-semibold">consectetur adipiscing</span> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['index', 'home_dining_cta1', 'text', 'Learn More'],
    ['index', 'home_dining_cta1_href', 'text', '/dining'],
    ['index', 'home_dining_cta2', 'text', 'View Details'],
    ['index', 'home_dining_cta2_href', 'text', '/dining'],
    ['index', 'booking_widget_html', 'html', ''],

    ['about', 'page_title', 'text', 'About'],
    ['about', 'hero_established', 'text', 'Established 2024'],
    ['about', 'hero_title_html', 'html', 'Lorem Ipsum <br/><span class="font-bold italic text-primary/90 site-hero-accent-text">Dolor Sit</span>'],
    ['about', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['about', 'hero_bg', 'image', $heroPlaceholder],
    ['about', 'story_title_html', 'html', 'Lorem Ipsum <br/><span class="font-semibold text-primary">Dolor Sit</span>'],
    ['about', 'story_p1', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['about', 'story_p2', 'text', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'],
    ['about', 'story_image', 'image', $detailPlaceholder],
    ['about', 'story_quote', 'text', '"Lorem ipsum dolor sit amet, consectetur adipiscing elit."'],
    ['about', 'values_kicker', 'text', 'Lorem Ipsum'],
    ['about', 'values_title', 'text', 'Dolor Sit Amet'],
    ['about', 'values_image', 'image', $galleryPlaceholder],
    ['about', 'values_card_icon', 'text', 'spa'],
    ['about', 'values_card_title', 'text', 'Lorem Ipsum Dolor'],
    ['about', 'values_card_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['about', 'values_card_link', 'text', 'Learn More'],
    ['about', 'values_card_link_href', 'text', '/amenities'],
    ['about', 'journey_title_html', 'html', 'Lorem <span class="font-bold italic text-primary">Ipsum</span>'],
    ['about', 'journey_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['about', 'team_kicker', 'text', 'Gallery'],
    ['about', 'team_heading', 'text', 'Lorem Ipsum'],
    ['about', 'team_intro', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['about', 'parallax_bg', 'image', $heroPlaceholder],
    ['about', 'parallax_quote', 'text', '"Lorem ipsum dolor sit amet."'],
    ['about', 'cta_title', 'text', 'Lorem Ipsum Dolor'],
    ['about', 'cta_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['about', 'cta_btn1', 'text', 'Explore Rooms'],
    ['about', 'cta_btn1_href', 'text', '/rooms'],
    ['about', 'cta_btn2', 'text', 'Contact Us'],
    ['about', 'cta_btn2_href', 'text', '/contact'],

    ['contact', 'page_title', 'text', 'Contact Us'],
    ['contact', 'intro_kicker', 'text', 'Lorem Ipsum'],
    ['contact', 'intro_title', 'text', 'Get in Touch'],
    ['contact', 'intro_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['contact', 'address_html', 'html', "123 Lorem Avenue<br/>\nIpsum City<br/>\nCountry"],
    ['contact', 'map_address', 'text', '123 Lorem Avenue, Ipsum City, Country'],
    ['contact', 'map_embed_url', 'text', ''],
    ['contact', 'directions_href', 'text', '#'],
    ['contact', 'concierge_phone', 'text', cms_default_setting('footer_phone')],
    ['contact', 'inquiries_email', 'text', cms_default_setting('contact_email')],
    ['contact', 'map_image', 'image', $galleryPlaceholder],
    ['contact', 'map_pin_label', 'text', 'Lorem Location'],

    ['hotel-policy', 'page_title', 'text', 'Hotel Policy'],
    ['hotel-policy', 'hero_kicker', 'text', 'Policy'],
    ['hotel-policy', 'hero_title', 'text', 'Hotel Policy'],
    ['hotel-policy', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'],
    ['hotel-policy', 'last_updated', 'text', 'Last updated: April 18, 2026'],
    ['hotel-policy', 'body_html', 'html', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h2>Lorem Ipsum</h2><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'],

    ['privacy-policy', 'page_title', 'text', 'Privacy Policy'],
    ['privacy-policy', 'hero_kicker', 'text', 'Legal'],
    ['privacy-policy', 'hero_title', 'text', 'Privacy Policy'],
    ['privacy-policy', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'],
    ['privacy-policy', 'last_updated', 'text', 'Last updated: April 18, 2026'],
    ['privacy-policy', 'body_html', 'html', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h2>Lorem Ipsum</h2><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'],

    ['terms-and-conditions', 'page_title', 'text', 'Terms & Conditions'],
    ['terms-and-conditions', 'hero_kicker', 'text', 'Legal'],
    ['terms-and-conditions', 'hero_title', 'text', 'Terms & Conditions'],
    ['terms-and-conditions', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'],
    ['terms-and-conditions', 'last_updated', 'text', 'Last updated: April 18, 2026'],
    ['terms-and-conditions', 'body_html', 'html', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h2>Lorem Ipsum</h2><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'],

    ['gallery', 'page_title', 'text', 'Gallery'],
    ['gallery', 'hero_kicker', 'text', 'Lorem Ipsum'],
    ['gallery', 'hero_title_html', 'html', 'VISUAL <span class="font-bold italic text-primary">LOREM</span>'],
    ['gallery', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['gallery', 'hero_bg', 'image', $heroPlaceholder],

    ['dining', 'page_title', 'text', 'Dining'],
    ['dining', 'hero_kicker', 'text', 'Dining'],
    ['dining', 'hero_title_html', 'html', 'Lorem Ipsum <br/><i class="font-light opacity-90">Dolor Sit</i>'],
    ['dining', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['dining', 'hero_hours', 'text', 'Open Daily: 00:00 - 00:00'],
    ['dining', 'hero_bg', 'image', $heroPlaceholder],
    ['dining', 'intro_vertical', 'text', 'Lorem Menus'],
    ['dining', 'chef_title_html', 'html', 'Lorem <br/> <span class="text-primary italic">Ipsum</span>'],
    ['dining', 'chef_body_html', 'html', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>'],
    ['dining', 'chef_signature', 'text', 'Lorem Ipsum'],
    ['dining', 'chef_main_img', 'image', $detailPlaceholder],
    ['dining', 'chef_circle_img', 'image', $galleryPlaceholder],
    ['dining', 'visual_title', 'text', 'Lorem Gallery'],
    ['dining', 'visual_link_href', 'text', '/gallery'],
    ['dining', 'menu_kicker', 'text', 'Lorem Menu'],
    ['dining', 'menu_heading', 'text', 'Lorem Ipsum'],
    ['dining', 'menu_quote', 'text', '"Lorem ipsum dolor sit amet."'],
    ['dining', 'cta_bg', 'image', $roomPlaceholder],
    ['dining', 'cta_title', 'text', 'Lorem Reservation'],
    ['dining', 'cta_body', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['dining', 'cta_btn1', 'text', 'Contact Us'],
    ['dining', 'cta_btn1_href', 'text', '/contact'],
    ['dining', 'cta_btn2', 'text', 'Explore Rooms'],
    ['dining', 'sticky_kicker', 'text', 'Lorem'],
    ['dining', 'sticky_subtitle', 'text', 'Ipsum'],

    ['rooms', 'page_title', 'text', 'Rooms & Suites'],
    ['rooms', 'hero_title', 'html', 'Lorem Spaces <br/><span class="font-bold italic font-serif">Dolor Sit</span>'],
    ['rooms', 'hero_subtitle', 'text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'],
    ['rooms', 'hero_bg', 'image', $heroPlaceholder],

    ['amenities', 'page_title', 'text', 'Amenities'],
];

$pageSections[] = ['about', 'timeline_json', 'json', $jsonEncode($cmsDefaults['about_timeline'])];
$pageSections[] = ['about', 'team_json', 'json', $jsonEncode($cmsDefaults['about_team'])];
$pageSections[] = ['gallery', 'items_json', 'json', $jsonEncode($cmsDefaults['gallery_items'])];
$pageSections[] = ['dining', 'masonry_json', 'json', $jsonEncode($cmsDefaults['dining_masonry'])];
$pageSections[] = ['dining', 'menu_json', 'json', $jsonEncode($cmsDefaults['dining_menu'])];
$pageSections[] = ['amenities', 'sections_json', 'json', $jsonEncode($cmsDefaults['amenities_sections'])];

$rooms = [
    [
        'title' => 'Lorem Room One',
        'slug' => 'lorem-room-one',
        'price' => 100.00,
        'room_type' => 'Standard',
        'max_guests' => 2,
        'short_description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'description' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n\nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        'main_image' => $roomPlaceholder,
        'gallery_images' => [$detailPlaceholder, $galleryPlaceholder],
        'features' => ['35 SQM', 'Queen Bed', 'City View', 'Wi-Fi'],
        'size' => '35 SQM',
        'location' => 'City View',
        'is_featured' => 1,
        'display_order' => 10,
    ],
    [
        'title' => 'Lorem Room Two',
        'slug' => 'lorem-room-two',
        'price' => 150.00,
        'room_type' => 'Suite',
        'max_guests' => 3,
        'short_description' => 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'description' => "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n\nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        'main_image' => $detailPlaceholder,
        'gallery_images' => [$roomPlaceholder, $galleryPlaceholder],
        'features' => ['48 SQM', 'King Bed', 'Lounge Area', 'Wi-Fi'],
        'size' => '48 SQM',
        'location' => 'Upper Floor',
        'is_featured' => 1,
        'display_order' => 20,
    ],
    [
        'title' => 'Lorem Room Three',
        'slug' => 'lorem-room-three',
        'price' => 220.00,
        'room_type' => 'Premium',
        'max_guests' => 4,
        'short_description' => 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
        'description' => "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
        'main_image' => $galleryPlaceholder,
        'gallery_images' => [$roomPlaceholder, $detailPlaceholder],
        'features' => ['60 SQM', 'Twin Lounge', 'Corner View', 'Wi-Fi'],
        'size' => '60 SQM',
        'location' => 'Corner View',
        'is_featured' => 1,
        'display_order' => 30,
    ],
];

return [
    'site_settings' => $siteSettings,
    'page_sections' => $pageSections,
    'rooms' => $rooms,
];
